
pipeline {

    agent any

    tools {
        maven "Maven"
        //docker "Docker"
        jdk "openjdk-14"
    }

    stages {
        stage('Maven Install') {
          steps {
            sh 'mvn clean install'
          }
        }
        stage('Docker Build') {
          agent any
              steps {
                sh "pwd"
                  dir("${env.WORKSPACE}/data-service") {
                    sh "pwd"
                    sh '/usr/local/bin/docker build -t kumar/data-service-test:$BUILD_NUMBER .'
                  }
                  sh "pwd"
                echo 'Docker build completed'
              }
        }
    }
}