
pipeline {
    agent any

    tools {
        maven "Maven"
        jdk "openjdk-14"
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn clean compile package org.sonarsource.scanner.maven:sonar-maven-plugin:RELEASE:sonar  -Dsonar.login=9c5fcea336ecf77f90ab404798832d89732e04f9 -f ./data-service/pom.xml'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn clean compile package -f ./data-service/pom.xml'
            }
            post {
                always {
                    archiveArtifacts '**/*.jar'
                }
            }
        }
    }
}