pipeline {

	agent any

	environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub-cred')
	}

	stages {
		stage('Initialize')
		    {
			def dockerHome = tool 'docker'
			env.PATH = "${dockerHome}/bin:${env.PATH}"
		    }

		stage('Build') {
			steps {
				sh 'docker build -t kumarch0601/mynginx:latest .'
			}
		}

		stage('Login') {

			steps {
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
			}
		}

		stage('Push') {

			steps {
				sh 'docker push kumarch0601/mynginx:latest'
			}
		}
	}

	post {
		always {
			sh 'docker logout'
		}
	}
}
